site_name: Rotoforge
site_description: Open source/hardware additive friction stir deposition 3D printer
site_author: Rotoforge
site_url: https://rotoforge.com
theme: readthedocs
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
docs_dir: source
site_dir: docs
nav:
  - 'Introduction': 'index.md'
  - 'Project Brief': 'project-brief.md'
  - 'Roadmap and Outstanding Tasks': 'roadmap.md'
  - 'Bill Of Materials': 'bom.md'
  - 'Assembly' : 'assembly.md'
